#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.2
#  in conjunction with Tcl version 8.6
#    Nov 15, 2022 11:46:13 AM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import tela

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tela.Toplevel1(_top1)
    root.mainloop()

def Carregar(*args):
    print('tela_support.Carregar')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Enviar(*args):
    print('tela_support.Enviar')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    tela.start_up()




